### ISSUE TITLE
Migrate Lufdaten.py to Sensors Community (luftdaten.py)

### ISSUE THREAD

**Issue by frankpanduh** [pimoroni/enviroplus-python#106]
Looks like "luftdaten" became "sensors community". The luftaden.py still makes connections but appears to make issues when signing up because the site has migrated to sensors.community. The website https://luftaden.info still exists but when you arrive to the webpage it tells you it also moved to "https://sensor.community/". 

Luftdaten: 

https://github.com/opendata-stuttgart/luftdaten.info

Sensors Community: 
https://github.com/opendata-stuttgart/sensor.community

**Comment by Gadgetoid** [comment]
https://github.com/pimoroni/enviroplus-python/pull/110/files fixed this for luftdaten.py but - not to self - needs also fixing for the new luftdaten_combined.py
