### ISSUE TITLE
BME280 - Pressure / Humidity Incorrect Readings

### ISSUE THREAD

**Issue by myte77** [pimoroni/enviroplus-python#116]
I've been using my enviro for a couple of years, writing out to InfluxDB no problem. Today however, humidity has started reading 0 and pressure is way too high. It just dropped off, everything else seems as normal. Anyone else have this or can recommend a fix?
![Screenshot 2022-07-21 062129](https://user-images.githubusercontent.com/109716486/180135694-777ba7fa-8c28-4919-9da8-4351a5b81aa3.png)

**Comment by myte77** [comment]
Sorted it. It was following a power cut. Could have been something that affected it. Just unplugged everything and reconnected and all back up.

**Comment by andypiper** [comment]
Good to close?

**Comment by myte77** [comment]
All good.. thank you.
