### ISSUE TITLE
Suddenly not starting, reporting an issue with `get_pin`

### ISSUE THREAD

**Issue by cmsimike** [pimoroni/enviroplus-python#134]
Hi,

This has been working on my RasPi for a few years now. Suddenly trying to start it, I'm getting:
```bash
  File "/home/pi/.virtualenvs/pimoroni/lib/python3.9/site-packages/enviroplus/gas.py", line 98, in read_all
    setup()
  File "/home/pi/.virtualenvs/pimoroni/lib/python3.9/site-packages/enviroplus/gas.py", line 67, in setup
    _heater = gpiodevice.get_pin("GPIO24")
TypeError: get_pin() missing 2 required positional arguments: 'label' and 'settings'
```

https://github.com/pimoroni/gpiodevice-python/blame/3adc533e2e860c8f23042fbf50831c8444c192ea/gpiodevice/__init__.py#L150

Seems like these parameters are required.

**Comment by Gadgetoid** [comment]
This was incredibly dumb on my part and I'm pushing a fix now.
