### ISSUE TITLE
python3 not supported yet

### ISSUE THREAD

**Issue by cipy** [pimoroni/enviroplus-python#21]
> $ python3 enviroplus-python/examples/all-in-one.py 

Displays readings from all of Enviro plus' sensors

Press Ctrl+C to exit!

Traceback (most recent call last):
  File "enviroplus-python/examples/all-in-one.py", line 143, in <module>
    cpu_temp = get_cpu_temperature()
  File "enviroplus-python/examples/all-in-one.py", line 96, in get_cpu_temperature
    return float(output[output.index('=') + 1:output.rindex("'")])
TypeError: argument should be integer or bytes-like object, not 'str'

**Comment by takkaria** [comment]
The fix for this with python3 is to add an extra output.decode() line in before the return:

```
def get_cpu_temperature():
    process = Popen(['vcgencmd', 'measure_temp'], stdout=PIPE)
    output, _error = process.communicate()
    output = output.decode()
    return float(output[output.index('=') + 1:output.rindex("'")])
```
