### ISSUE TITLE
Read ADC

### ISSUE THREAD

**Issue by psycik** [pimoroni/enviroplus-python#44]
When will this be possible? The current adc example only reads ref/gnd and the library has no access to the 4th input. I am looking to use my analog co2 sensor with this.

**Comment by Gadgetoid** [comment]
Our ADS1015 library is very strongly (probably mistakenly so) biased toward our ADS1015 breakout which includes an onboard reference connected to input 3. Thus the name `ref/gnd` being erroneously used in the library.

`ref` is actually just `AIN3`, and on Enviro+ this is connected via a 330Ohm current limiting resistor to the ADC breakout pin.
