### ISSUE TITLE
Understanding the MICS output

### ISSUE THREAD

**Issue by CalmArms** [pimoroni/enviroplus-python#47]
Hey there, I really appreciate the work that's gone into the Enviro+ and the library, it's a nifty piece of kit!

I'm having a bit of trouble at the moment translating the readings from the MICS sensor into something meaningful beyond increasing or decreasing air quality relative to the environment it started measuring in.

Are there are any reference materials for translating the Ohms output by each of the sensors to some bands for measuring air quality? For example, if the Oxidising output was 4570 Ohms, what does that mean in itself? Is that normal levels? Dangerous levels? Or does it not intrinsically mean anything?

If the latter, am I right in thinking that to measure the air quality of a particular area, I first need to start the sensor in a "clean" room to set the baseline?

Any guidance is much appreciated!

**Comment by nophead** [comment]
My experience is that the gas sensors don't give any meaningful absolute values because temperature, pressure and humidity massively affect the readings. 

![image](https://user-images.githubusercontent.com/566149/72389537-8058b600-3720-11ea-8f28-a0c7f501f6d3.png)

Here you can see the gas sensors seem to be pretty much the inverse of humidity. Was there a massive increase in pollution, or simply a drop in humidity?

**Comment by CalmArms** [comment]
Ah... well observed @nophead. I'll leave the issue open for a bit in case anybody else is able to pitch in, but I think you're probably right.

**Comment by Gadgetoid** [comment]
This is- indeed- correct. These sensors don't produce much meaningful information without context- that may be either known baseline or calibration. You can use other sources to quantity a baseline measurement- IE: measure for a day and go and check other data for confirmation on what your measurements should be showing- and then use variation upon that measurement to infer data points from your future readings.

Regarding @nophead's comment about the gas displaying the inverse of humidity- I don't know off the top of my head, but the effects of other environmental factors on gas readings should be well documented and/or studied somewhere. I usually rely on @sandyjmacdonald and his super science background to dig these up and turn them into something a mere layperson such as myself can understand. 😆 

I think we can probably do better with explaining the shortfalls of these sensor packages and how best to use them, given they are effectively uncalibrated, raw sensors. In an ideal world they would be calibrated, but - at least in the case of gas sensors - this requires obtaining known gas mixes and exposing the installed sensor to them.

**Comment by nophead** [comment]
This is a long term graph:

![image](https://user-images.githubusercontent.com/566149/72567120-1faab400-38ad-11ea-9a9c-c7fc72c6d7f1.png)

If you look at the oxi trace it goes from 10K, through 20K, which is supposed to be the nominal value, rises steadily over time and is now regularly over 400K. Note it got moved from the UK inside to Tenerife outside where the temperature jumps in the middle. I can't make any sense of the reading unless oxidising gases are steadily increasing over time.
