### ISSUE TITLE
[Question] - Enviro example with icons

### ISSUE THREAD

**Issue by SirLancelotDuLac** [pimoroni/enviroplus-python#52]
Hi there

Just a question: the example shown on the store page for Enviro, the one with icons and sensor values with the orange backgroufnd. Where can i find it?

Thanks

**Comment by roscoe81** [comment]
You should be able to find it here https://github.com/pimoroni/enviroplus-python/blob/enviro-non-plus/examples/weather-and-light.py

**Comment by SirLancelotDuLac** [comment]
Great...forgot to see the branches........
Thanks
