### ISSUE TITLE
noise.py amp_total wrong

### ISSUE THREAD

**Issue by MASHtm** [pimoroni/enviroplus-python#61]
get_noise_profile() always returns the same value for amp_total.
     amp_total = (low + mid + high) / 3.0
low, mid, high are parameters. Shouldn't that be
     amp_total = (amp_low + amp_mid + amp_high) / 3.0
?

**Comment by Gadgetoid** [comment]
It looks like you're correct! Good spot.

**Comment by Gadgetoid** [comment]
Should be fixed as of - https://github.com/pimoroni/enviroplus-python/pull/62
