### ISSUE TITLE
Install misses package 

### ISSUE THREAD

**Issue by java-artisan** [pimoroni/enviroplus-python#63]
The install fails because it can't find a package named 'ffi'. For both Python 2 and 3.

This is fixed by running:
`sudo apt-get install python3-cffi python-cffi`
And restarting the install.

**Comment by Hellspawny** [comment]
Sadly, python3-ccfi isn't available at the moment.

`sudo apt-get install python3-ccfi`
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-ccfi

**Comment by java-artisan** [comment]
My mistake, that's a typo. I copy/pasted the Python 2 package name for Python 3. The instruction should read:
`sudo apt-get install python3-cffi python-cffi`

**Comment by Hellspawny** [comment]
Thank you, should have recognized it myself.
