### ISSUE TITLE
weather-and-light example fails with SyntaxError

### ISSUE THREAD

**Issue by markmcgookin** [pimoroni/enviroplus-python#78]
Clean Raspbian Lite install, one line installer for dependencies, clone this repo to directory, navigate to repo and call "python weather-and-lite.py' on a raspberry pi zero causes the following error

```
File "weather-and-light.py", line 380
SyntaxError: Non-ASCII character '\xc2' in file weather-and-light.py on line 380, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Adding 

`# -*- coding: utf-8 -*-`

to the file removes this issue, but then you get the following error:

```
  File "weather-and-light.py", line 381
    temp_string = f"{corr_temperature:.0f}°C"
                                             ^
SyntaxError: invalid syntax
```
Removing the `°C` still causes this error

**Comment by Gadgetoid** [comment]
If you're running in python 2.x then f-strings will throw a syntax error. I'm not sure whether we want to continue worrying about python 2.x or try to field these issues and force people onwards and upwards. Right now it's still bafflingly the default for the "python" command in Raspberry Pi OS, and the whole thing is really holding back use of nice cozy Python 3.x features. It's a nightmare, for sure!

Not sure whether the solution here is to throw some kind of "You should really be using Python 3.x" warning in examples, or relent and remove Python 3.x niceties. It's tricky!

**Comment by Gadgetoid** [comment]
Looks like removing the Python 3.x niceties is a lost cause, since even with all the f-strings replaced it will fail with an error on the `astral` dependency, which despite installing for me under Python 2.7 doesn't support Python 2.7. Yay!

*Furthermore* since the entire file fails to parse in Python 2, it's difficult to include any kind of trap to catch running in Python 2.

Except- perhaps- *deliberately* causing a syntax error:

![image](https://user-images.githubusercontent.com/1746967/88913922-bc391000-d259-11ea-99a2-2c8e102e3a19.png)

**Comment by markmcgookin** [comment]
Yea, I stupidly assumed `$python weather-and-light.py` would have worked, I didn't expect python 2 to be the default on a fresh install of rpi-os. Running it with `$python3 weather-and-light.py` works fine, so I'm happy. Yeah a helpful error that just says 'run this with python3 you caveman!' would really have helped speed up solving this though, so that would be a perfectly acceptable fix in my book. 

Cooking on gas now though. Thanks for the help. I'll leave the issue open and let you decide if you want to close it under a commit using a more helpful error message or not.

![IMG_7473-1](https://user-images.githubusercontent.com/1053345/88915054-809f4580-d25b-11ea-9c93-e270e00a6797.jpg)

**Comment by markmcgookin** [comment]
This is really an issue with python versions, Phil's latest commit with a warning is a fine way to show what's wrong and avoid the issue. Closing as solved.
