### ISSUE TITLE
Support for other boards besides raspberry Pi with 40 pin gpio

### ISSUE THREAD

**Issue by saket424** [pimoroni/enviroplus-python#94]
I got a Google Coral Dev mini board with the same pinout as a raspberry pi0 with I2C support

https://coral.ai/docs/dev-board-mini/get-started/

What changes are needed to get the enviro+ python library working on a non-raspberry pi board?

**Comment by Gadgetoid** [comment]
I'm afraid I don't know. We pretty much exclusively support RPi and don't have the people-power to step outside that comfortable bubble. This question would probably be best raised on their support or community channels.
